/*
CREATE [OR REPLACE] TRIGGER trigger_name
{BEFORE | AFTER } triggering_event ON table_name
[FOR EACH ROW]
[FOLLOWS | PRECEDES another_trigger]
[ENABLE / DISABLE ]
[WHEN condition]
DECLARE
    declaration statements
BEGIN
    executable statements
EXCEPTION
    exception_handling statements
END;
*/

--1. Create table
CREATE TABLE words (
    word_id   NUMBER
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    word_name VARCHAR(100) NOT NULL
);

INSERT INTO words ( word_name ) VALUES ( 'Hello' );
INSERT INTO words ( word_name ) VALUES ( 'Hi' );
INSERT INTO words ( word_name ) VALUES ( 'Home' );

select * from words;

create or replace trigger mytrigger
after update or delete ON suppliers declare l_transaction
